#!/bin/bash
#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --cpus-per-task=1        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --mem-per-cpu=2G         # memory per cpu-core (4G is default)
#SBATCH --time=01:00:00          # total run time limit (HH:MM:SS)


mkdir -p out_dir
mkdir -p out_data
mkdir -p home

# Add permissions to read main.m
chmod a+r main.m
chmod a+x main.m 

# 1) Run code local - Matlab MCR
# /usr/local/brainstorm3/bin/R2023a/brainstorm3.command /home/natalia/app-brainstorm-MEGprocessing main.m local

# 2) Run code singularity
# singularity run -e --bind `pwd`/home:/home/$USER docker://nicomm77/neurodockernmm:v1 main.m local

# 3) Run code local - Matlab interpreter
#/Applications/MATLAB_R2022a.app/bin/matlab -nodisplay -r main

# 4) Run code singularity with sif uploaded
singularity exec --bind `pwd`/home:/home/$USER /network/iss/brainlife/users/brlife/containers/neurodockernmm_v1.sif /opt/brainstorm/bin/R2023a/brainstorm3.command /opt/matlab_runtime/R2023a
 main.m local

